version: '3.8'
services:
  db-app:
    build: ./db-app
    container_name: postgre
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my_network

  provider-app:
    build: ./provider-app
    container_name: provider-app
    volumes:
      - ./provider-app:/app
    environment:
      - name=3001
    ports:
      - "3001:3001"
    networks:
      - my_network

  client-app:
    build: ./client-app
    container_name: client-app
    volumes:
      - ./client-app:/app
    environment:
      - name=4000
    ports:
      - "4000:4000"
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  db_data:


networks:
  my_network:
    driver: bridge
